multipass: true

plugins:
  - convertPathData:
      floatPrecision: 3
      noSpaceAfterFlags: false

  - sortAttrs:
      order:
        - role
        - viewBox
      xmlnsOrder: end

  - convertShapeToPath:
      convertArcs: true

  - mergePaths:
      force: true
      noSpaceAfterFlags: false

  - removeTitle: true

  - addAttributesToSVGElement:
      attributes:
        - role: img
  - removeUnknownsAndDefaults:
      keepRoleAttr: true

  - removeDoctype
  - removeXMLProcInst
  - removeComments
  - removeMetadata
  - removeXMLNS
  - removeEditorsNSData
  - cleanupAttrs
  - inlineStyles
  - minifyStyles
  - convertStyleToAttrs
  - cleanupIDs
  - prefixIds
  - removeRasterImages
  - removeUselessDefs
  - cleanupNumericValues
  - cleanupListOfValues
  - convertColors
  - removeNonInheritableGroupAttrs
  - removeUselessStrokeAndFill
  - removeViewBox
  - cleanupEnableBackground
  - removeHiddenElems
  - removeEmptyText
  - moveElemsAttrsToGroup
  - moveGroupAttrsToElems
  - collapseGroups
  - convertTransform
  - removeEmptyAttrs
  - removeEmptyContainers
  - removeUnusedNS
  - removeDesc
  - removeDimensions
  - removeAttrs
  - removeAttributesBySelector
  - removeElementsByAttr
  - addClassesToSVGElement
  - removeStyleElement
  - removeScriptElement
  - removeOffCanvasPaths
  - reusePaths
